### ISSUE TITLE
Does context matter?

### ISSUE THREAD

**Issue by xiaoleihuang** [dmort27/epitran#12]
Should I feed the individual words to the epitran or a whole sentence to the epitran? 
Are there any rules using contexts to transliterate the words?

**Comment by dmort27** [comment]
Epitran expects word length tokens. That is because some of the rules make reference to word boundaries and these are (currently) defined in terms of the beginning and end of the token. For some languages, you will get reasonable results feeding the whole sentence to Epitran, but this is not reliable.
