### ISSUE TITLE
Flite error when trying to transliterate english

### ISSUE THREAD

**Issue by Qwerty-Space** [dmort27/epitran#15]
![image](https://user-images.githubusercontent.com/6967592/44809910-00cc5480-abc8-11e8-81bc-fe6d8ac6824a.png)
This should speak for itself tbh.

Python 3.7.0, latest epitran from pypi.

**Comment by Qwerty-Space** [comment]
So, it requires flite to transliterate english?  Why is that?

**Comment by dmort27** [comment]
It requires flite's G2P system because a rule based G2P system like default Epitran is not suitable for an orthography as opaque as English. Rather than writing our own statistical G2P system, we borrowed one from Flite. As for your problem, I haven't seen this problem on any of the machines or operating systems on which I have tested Epitran. It seems that there is some difference between you PATH as accessible to the shell and your path as accessible to the subprocess module. It's hard for me to debug without knowing more about your machine and your installation.
