### ISSUE TITLE
The same word is transliterated differently

### ISSUE THREAD

**Issue by gcelano** [dmort27/epitran#61]
I got a strange transliteration for Italian:

`abiud d͡ʒenerɔ eliat͡ʃim eliat͡ʃim ɡenerɔ asor`

`ɡenerɔ` should be like `d͡ʒenerɔ`. This happens if the string is part of a much larger string, but not when it is transliterated in isolation (i.e., only that string).

**Comment by dmort27** [comment]
This is due to the fact that Epitran is designed only to be used on word-length tokens (not on space-delimited strings). Then is necessary because of the range of orthographies (with different orthographic conventions) supported. It knows what the beginning and end of a word are only because they are the beginning and end of a string. Thus, the two different transliterations are to be expected.
