### ISSUE TITLE
English IPA translation

### ISSUE THREAD

**Issue by tobyr-ai** [dmort27/epitran#66]
I am trying to use Epitran to create IPA conversions for English sentences, and it doesn't produce results I expect for some common words.

```
import epitran
epi = epitran.Epitran('eng-Latn')
epi.transliterate("was does buzz")
'wɑz dowz bʌz'
```

Note that IPA for `does` contains a `w`. Looking through dictionaries, I find `ˈdəz`, `dɪz`. When all three are put into a simple IPA reader, the dictionary versions sound correct and epitran's translation sounds wrong.

**Comment by dmort27** [comment]
@tobyr-ai , I have replicated your error. The output from this code *should be* `"wʌz dʌz bʌz"` (note that, in the system of IPA transcription usually used for American English, which is what Epitran is supposed to use, /ə/ only occurs in unstressed syllables and the stressed equivalent is /ʌ/).

I can't fix this problem directly since Epitran outsources English G2P to the `flite` speech synthesis system. You might raise an issue on their Github repo.
