### ISSUE TITLE
Epitran sometimes give weird outputs.

### ISSUE THREAD

**Issue by rizveeredwan** [dmort27/epitran#75]
``import epitran``
``epi = epitran.Epitran('eng-Latn')``
``print (epi.transliterate('beautiful'))``
The output of word ``beautiful`` is ``bjutəfəl``. But according to English IPA ``ə`` actually represents different phoneme.  I have used flight for English transliteration. Is there some kind of bug in flight for which an error prone transliteration gets output. Similar goes for word ``Quran`` also.

**Comment by dmort27** [comment]
Speaking as a phonologist, the output for American English _beautifuyl_ is actually correct (at least, the vowels are; for many American English speakers, the <t> would be flapped). Both the penultimate and ultimate vowels are unstressed and mid-central. I think this may not be the case in some varieties of British English.

However, these are not issues that can be fixed within Epitran itself since Epitran relies on Flite for English g2p.
